version: '3.8'

services:
  laptop-service:
    build: ./laptop_service
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=kiemtra01_laptop
      - DB_USER=postgres
      - DB_PASSWORD=12345678
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mobile-service:
    build: ./mobile_service
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=kiemtra01_mobile
      - DB_USER=postgres
      - DB_PASSWORD=12345678
    extra_hosts:
      - "host.docker.internal:host-gateway"

  customer-service:
    build: ./customer_service
    ports:
      - "8003:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=kiemtra01_customer
      - DB_USER=root
      - DB_PASSWORD=12345678
    extra_hosts:
      - "host.docker.internal:host-gateway"

  staff-service:
    build: ./staff_service
    ports:
      - "8004:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=kiemtra01_staff
      - DB_USER=root
      - DB_PASSWORD=12345678
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    build: ./api_gateway
    ports:
      - "8005:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
