services:
  neo4j:
    image: neo4j:5.20
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  laptop-service:
    build: ./laptop_service
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=kiemtra01_laptop
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - NEO4J_BOLT_URL=bolt://neo4j:password@neo4j:7687
    depends_on:
      - neo4j
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mobile-service:
    build: ./mobile_service
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=kiemtra01_mobile
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - NEO4J_BOLT_URL=bolt://neo4j:password@neo4j:7687
    depends_on:
      - neo4j
    extra_hosts:
      - "host.docker.internal:host-gateway"

  customer-service:
    build: ./customer_service
    ports:
      - "8003:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=kiemtra01_customer
      - DB_USER=root
      - DB_PASSWORD=12345678
    extra_hosts:
      - "host.docker.internal:host-gateway"

  staff-service:
    build: ./staff_service
    ports:
      - "8004:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=kiemtra01_staff
      - DB_USER=root
      - DB_PASSWORD=12345678
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    build: ./api_gateway
    ports:
      - "8005:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  neo4j_data:
  neo4j_logs:
