version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kiemtra01
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=kiemtra01
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
